# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='multiPack.proto',
  package='',
  serialized_pb='\n\x0fmultiPack.proto\"(\n\nMultiPacks\x12\x1a\n\x05packs\x18\x01 \x03(\x0b\x32\x0b.SinglePack\"*\n\nSinglePack\x12\x0e\n\x06header\x18\x01 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c')




_MULTIPACKS = descriptor.Descriptor(
  name='MultiPacks',
  full_name='MultiPacks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='packs', full_name='MultiPacks.packs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=59,
)


_SINGLEPACK = descriptor.Descriptor(
  name='SinglePack',
  full_name='SinglePack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='SinglePack.header', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='SinglePack.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=103,
)

_MULTIPACKS.fields_by_name['packs'].message_type = _SINGLEPACK
DESCRIPTOR.message_types_by_name['MultiPacks'] = _MULTIPACKS
DESCRIPTOR.message_types_by_name['SinglePack'] = _SINGLEPACK

class MultiPacks(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MULTIPACKS
  
  # @@protoc_insertion_point(class_scope:MultiPacks)

class SinglePack(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SINGLEPACK
  
  # @@protoc_insertion_point(class_scope:SinglePack)

# @@protoc_insertion_point(module_scope)
